"project_id": "481855" 
"api_token": "e2a8bfdcafafbcd27e8e4c947a3cc2da8653fdf37742a77ad8bc6997654cdde471d2daa5e74e975e"
"base_path": "/webdocs"
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true
"files": [
  {
    "source": "/pages/**/**.en.(js|mdx)",
    "translation": "/%original_path%/%file_name%.%two_letters_code%.%file_extension%" 
  }
]